name:                postgresql-tx-example
version:             0.0.0.0
github:              "simspace/postgresql-tx"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            A safe transaction monad for use with various PostgreSQL Haskell libraries.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- bytestring
- hspec
- monad-logger
- postgresql-libpq
- postgresql-query
- postgresql-simple
- postgresql-tx
- postgresql-tx-query
- postgresql-tx-simple
- postgresql-tx-squeal
- squeal-postgresql

tests:
  postgresql-tx-example-tests:
    main: Driver.hs
    source-dirs:
    - test
    build-tools:
    - hspec-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
