resolver: lts-15.6

packages:
- .
- example
- monad-logger
- persistent
- query
- simple
- squeal

extra-deps:
# {{{ postgresql-query
- git: git@github.com:Simspace/postgresql-query
  commit: b45346d7af5a5de6f083349ac1fcee830afe4112
# }}}

# {{{ squeal
- squeal-postgresql-0.6.0.2
- free-categories-0.2.0.0
# }}}
