resolver: lts-16.8

packages:
- .
- example
- libpq
- monad-logger
- persistent
- query
- random
- simple
- squeal

extra-deps:
- postgresql-simple-0.6.3
- postgresql-query-3.8.1

# {{{ squeal
- squeal-postgresql-0.7.0.1
- free-categories-0.2.0.2
# }}}
