name:                postgresql-tx-persistent
version:             0.0.0.0
github:              "simspace/postgresql-tx"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            A safe transaction monad for use with various PostgreSQL Haskell libraries.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- monad-logger
- persistent
- persistent-postgresql
- postgresql-tx

library:
  source-dirs: src
