name:                postgresql-tx-libpq
version:             0.2.0.0
github:              "simspace/postgresql-tx"
license:             BSD3
license-file:        LICENSE.md
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"
synopsis:            postgresql-tx interfacing for use with postgresql-libpq.
category:            Database
description:         Please see the README on GitHub at <https://github.com/simspace/postgresql-tx#readme>

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- postgresql-libpq
- postgresql-tx

library:
  source-dirs: src
